{{- range .Values.roles }}
---
{{- if eq .role_binding true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "ssr-operator.labels" $ | nindent 4 }}
  name: {{ include "ssr-operator.name" $ }}-{{ .name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ssr-operator.name" $ }}-{{ .name }}
subjects:
- kind: {{ .kind }}
  name: {{ include "ssr-operator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}