{{- range .Values.cluster_roles }}
---
{{- if eq .enabled true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ssr-operator.labels" $ | nindent 4 }}
  name: {{ include "ssr-operator.name" $ }}-{{ .name }}
rules: 
{{ toYaml .rules }}
{{- end }}
{{- end }}